version: '3.7'

mongo:
  image: treehouses/rpi-mongo:3
  restart: always
  init: true
  ports:
    - 27017:27017
  environment:
    MONGO_INITDB_ROOT_USERNAME: root
    MONGO_INITDB_ROOT_PASSWORD: example
